#Sales Analysis using DS Techniques

In [3]:
#Import the Librarys

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("Imported the Module")

Imported the Module

In [4]:
#Load the Sales Data

dataset_path=r"datasets\AusApparalSales4thQrt2020.csv"

df_SalesData=pd.read_csv(dataset_path)

df_SalesData.head() #7560 Rows

         Date        Time State     Group  Unit  Sales
0  1-Oct-2020     Morning    WA      Kids     8  20000
1  1-Oct-2020     Morning    WA       Men     8  20000
2  1-Oct-2020     Morning    WA     Women     4  10000
3  1-Oct-2020     Morning    WA   Seniors    15  37500
4  1-Oct-2020   Afternoon    WA      Kids     3   7500

1.	Data wrangling
a.	Ensure that the data is clean and free from any missing or incorrect entries.
○	Inspect the data manually to identify missing or incorrect information using the functions isna() and notna().
b.	Based on your knowledge of data analytics, include your recommendations for treating missing and incorrect data (dropping the null values or filling them).
c.	Choose a suitable data wrangling technique—either data standardization or normalization. Execute the preferred normalization method and present the resulting data. (Normalization is the preferred approach for this problem.)
d.	Share your insights regarding the application of the GroupBy() function for either data chunking or merging, and offer a recommendation based on your analysis.

Task 1-a
1.	Ensure that the data is clean and free from any missing or incorrect entries.
2	Inspect the data manually to identify missing or incorrect information using the functions isna() and notna().

In [5]:
#Data Wrangling

#Validate the Sales Data Data Types

df_SalesData.dtypes

#a.Ensure that the data is clean and free from any missing or incorrect entries.

#Inspect the data manually to identify missing or incorrect information using the functions isna() and notna().

print(f"Missing Values in each column:\n{df_SalesData.isna().sum()}") #no missing values in all the 6 columns

print(f"Non-Missing Values in each column:\n{df_SalesData.notna().sum()}") #7560 non-missing values in all the 6 columns

#Since there is no missing values and all the columns have values, the sales data is clean and proceed to next steps

Missing Values in each column:
Date     0
Time     0
State    0
Group    0
Unit     0
Sales    0
dtype: int64
Non-Missing Values in each column:
Date     7560
Time     7560
State    7560
Group    7560
Unit     7560
Sales    7560
dtype: int64

Task 1-b
b.	Based on your knowledge of data analytics, include your recommendations for treating missing and incorrect data (dropping the null values or filling them).

In [6]:
#Task 1-B,

df_SalesData.dropna(how="all", inplace=True) #drop the rows with all missing values, but there are no missing values in the dataset, so it will not drop any rows
df_SalesData.info() #No rows with all missing values, so the dataset remains unchanged with 7560 rows and 6 columns.


df_SalesData.fillna(df_SalesData["Sales"].mean(), inplace=True) #fill the missing values in the "Sales" column with the mean of the "Sales" column, but there are no missing values in the "Sales" column, so it will not fill any values
df_SalesData.info() #No missing values in the "Sales" column, so the dataset remains unchanged with 7560 rows and 6 columns.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7560 entries, 0 to 7559
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    7560 non-null   object
 1   Time    7560 non-null   object
 2   State   7560 non-null   object
 3   Group   7560 non-null   object
 4   Unit    7560 non-null   int64
 5   Sales   7560 non-null   int64
dtypes: int64(2), object(4)
memory usage: 354.5+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7560 entries, 0 to 7559
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    7560 non-null   object
 1   Time    7560 non-null   object
 2   State   7560 non-null   object
 3   Group   7560 non-null   object
 4   Unit    7560 non-null   int64
 5   Sales   7560 non-null   int64
dtypes: int64(2), object(4)
memory usage: 354.5+ KB

#Task 1-c
c.	Choose a suitable data wrangling technique—either data standardization or normalization. Execute the preferred normalization method and present the resulting data. (Normalization is the preferred approach for this problem.)

In [7]:
#Task 1-c, Choose a suitable data wrangling technique—either data standardization or normalization. Execute the preferred normalization method and present the resulting data. (Normalization is the preferred approach for this problem.)

#scale the range, Normalization is required when the numeric values are too far hence we need to scale the range of the numeric values to a standard range, such as 0 to 1, to ensure that all features contribute equally to the analysis and prevent any single feature from dominating the results.

#pip install scikit-learn

#from sklearn.preprocessing import MinMaxScaler
 
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
print("Working fine!")
 
scaler=MinMaxScaler() #Create an instance of the MinMaxScaler class, which will be used to perform normalization on the data.

#From Data from take sale and unit column to scale up.

df_SalesData[["Sales","Unit"]]=scaler.fit_transform(df_SalesData[["Sales","Unit"]]) #Apply the fit_transform method of the scaler object to the "Sales" and "Units" columns of the df_SalesData DataFrame. This will normalize the values in these columns to a range between 0 and 1.
df_SalesData[["Sales","Unit"]]

Working fine!

         Sales      Unit
0     0.095238  0.095238
1     0.095238  0.095238
2     0.031746  0.031746
3     0.206349  0.206349
4     0.015873  0.015873
...        ...       ...
7555  0.190476  0.190476
7556  0.206349  0.206349
7557  0.206349  0.206349
7558  0.142857  0.142857
7559  0.174603  0.174603

[7560 rows x 2 columns]

Task 1-D : d.	Share your insights regarding the application of the GroupBy() function for either data chunking or merging, and offer a recommendation based on your analysis.

In [ ]:
#Task 1-d

state_sales=df_SalesData.groupby("State")["Sales"].sum().reset_index() #Group the df_SalesData DataFrame by the "State" column and calculate the sum of the "Sales" column for each state. The result is stored in a new DataFrame called state_sales, which contains two columns: "State" and "Sales".
state_sales.head(4) #Display the first 4 rows of the state_sales DataFrame to verify the results of the grouping and summation operation.

print("State-wise total sales:")
print(state_sales) #list the total sales for each state,.

#Sort the values by state to know the state with the highest sales.
state_sales_sorted=state_sales.sort_values(by="Sales", ascending=False) #Sort the state_sales DataFrame by the "Sales" column in descending order, so that the states with the highest sales appear at the top of the DataFrame. The sorted DataFrame is stored in a new variable called state_sales_sorted.
print(state_sales_sorted) #Display the rows of the state_sales_sorted

State-wise total sales:
  State       Sales
0   NSW  441.714286
1    NT  109.079365
2   QLD  177.888889
3    SA  339.412698
4   TAS  110.222222
5   VIC  635.968254
6    WA  106.365079

  State       Sales
5   VIC  635.968254
0   NSW  441.714286
3    SA  339.412698
2   QLD  177.888889

2.	Data analysis

3.	Data visualization

4.	Report generation